input21<-as.data.frame(readLines("day21.txt"))
input21<-tidyr::separate(input21,col=1,into=c("on_off","coords"),sep=" ")
input21<-tidyr::separate(input21,col="coords",into=c("x","y","z"),sep=",")
input21$x<-stringr::str_replace(input21$x,"x=","")
input21$y<-stringr::str_replace(input21$y,"y=","")
input21$z<-stringr::str_replace(input21$z,"z=","")
input21<-tidyr::separate(input21,col="x",into=c("x_min","x_max"),sep="\\.\\.")
input21<-tidyr::separate(input21,col="y",into=c("y_min","y_max"),sep="\\.\\.")
input21<-tidyr::separate(input21,col="z",into=c("z_min","z_max"),sep="\\.\\.")
xmin<-min(input21$x_min)
xmax<-max(input21$x_max)
ymin<-min(input21$y_min)
ymax<-max(input21$y_max)
zmin<-min(input21$z_min)
zmax<-max(input21$z_max)
